-- {"id":923826,"ver":"1.0.0","libVer":"1.0.0","author":"pxkazuki","dep":["Madara>=2.2.0"]}

return Require("Madara")("https://meionovel.id", {
	id = 923826,
	name = "MeioNovel",
	imageURL = "https://meionovel.id/wp-content/uploads/2017/10/sampul-meio111-1.png",
	searchHasOper = true,
	genres = {
		"Action",
		"Adventure",
		"Comedy",
		"Cooking",
		"Drama",
		"Ecchi",
		"Fanfiction",
		"Fantasy",
		"Gender Bender",
		"Harem",
		"Historical",
		"Horror",
		"Isekai",
		"Josei",
		"Magic",
		"Martial Arts",
		"Mature",
		"Mecha",
		"One shot",
		"Mystery",
		"Psychological",
		"Reverse Harem",
		"Romance",
		"School Life",
		"Sci-fi",
		"Seinen",
		"Shoujo",
		"Shoujo Ai",
		"Shounen",
		"Shounen Ai",
		"Slice of Life",
		"Smut",
		"Sports",
		"Supernatural",
		"Tragedy",
		"Virtual Reality",
		"Wuxia",
		"Xianxia",
		"Xuanhuan",
		"Yuri"
	}
})
